# Generated by Django 4.2.29 on 2026-03-16 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0003_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
