# Generated by Django 4.2.29 on 2026-03-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_alter_reservation_check_in_date_and_more'),
        ('listings', '0004_property_viewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deal_confirmed_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_deal_closed', to='messaging.reservation'),
        ),
        migrations.AddField(
            model_name='property',
            name='deal_done',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
