# Generated by Django 4.2.29 on 2026-03-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_property_deal_confirmed_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('rented', 'Rented'), ('refused', 'Refused'), ('deleted', 'Deleted')], db_index=True, default='pending', max_length=20),
        ),
    ]
