# Generated by Django 4.2.29 on 2026-03-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['deleted_at'], name='messaging_c_deleted_338054_idx'),
        ),
    ]
