# Generated by Django 4.2.29 on 2026-03-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_inquirymessage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inquiry',
            name='messaging_i_to_user_3b9bc8_idx',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='is_read',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='from_user_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='to_user_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['to_user', 'to_user_read'], name='messaging_i_to_user_8c8e19_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['from_user', 'from_user_read'], name='messaging_i_from_us_ce1a43_idx'),
        ),
    ]
