# Generated by Django 4.2.29 on 2026-03-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_remove_inquiry_messaging_i_to_user_3b9bc8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirymessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
