# Generated by Django 4.2.29 on 2026-03-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_alter_reservation_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deleted_for_guest_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when guest deleted from their dashboard (soft delete)', null=True),
        ),
    ]
