# Generated by Django 4.2.29 on 2026-03-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_reservation_deleted_for_guest_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inquiry',
            name='messaging_i_from_us_ce1a43_idx',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='from_user_read',
        ),
    ]
