# Generated by Django 4.2.29 on 2026-03-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_remove_inquiry_messaging_i_from_us_ce1a43_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contactmessage',
            name='messaging_c_deleted_338054_idx',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='deleted_at',
        ),
    ]
